import Head from 'next/head';
import Banner from '../components/Banner';
import Navbar from '../components/Navbar';
import Text from '../components/Text';
import { light } from '../styles/js-colors';
import styles from '../styles/Home.module.scss';
import Header from '../components/Header';
import Container from '../components/Container';
import Button from '../components/Button';

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Clive Roberts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Banner>
        <Container classnames={styles.BannerContainer}>
          <Text color={light} fontSize={28} classnames={styles.BannerText}>
            I am an Australian artist born in 1955 residing in the country side of France.
          </Text>
          <Button classnames={styles.BannerButton}>Learn More</Button>
        </Container>
      </Banner>
      <Container variant="center">
        <Header fontSize={36}>Featured Work</Header>
      </Container>
    </div>
  );
}
